version: '3.8'
services:
  app:
    container_name: springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mypostgresdb
  mypostgresdb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=7142
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fashionblog-docker